-
        kind: Application
        name: my-app
        gitRepo: 'https://github.com/perxsimuvo0ke2/solid-giggle.git'
        gitBranch: main
        gitApplicationPath: /
        dockerCompose:
            build:
                context: .
                dockerfile: ./Dockerfile
            #    target: prod
            #    args:
            #        APP_NAME: '{{env.varGroups.app.NAME}}'
            #    secrets:
            #        NPM_TOKEN: '{{env.varGroups.app.NPM_TOKEN}}'
            environmentVariablesGroups:
                - var-group-1
                - var-group-2
            environment:
                MY_VAR: value
                OTHER_VAR: 2
            entrypoint: /bin/sh
            command:
                - -c
                - 'echo "starting..." && ./myscript.sh"
            ports:
                - '80:8080'
            deploy:
                replicas: 3
                resources:
                    limits:
                        cpus: '2'
                        memory: '10000M'
                    reservations:
                        cpus: '0.50'
                        memory: '5000M'
        
